extends: google
env:
  browser: true
  serviceworker: true
  worker: true
globals:
  angular: true
rules:
  # Rules we want to add
  quotes:
    - 2
    - single
  # Rules we want to ignore
  max-nested-callbacks: 0
  no-warning-comments: 0
  require-jsdoc: 0
  camelcase: 0
  max-len: 0
  object-curly-spacing: 0
  one-var: 0
  arrow-parens: 0
