sudo: false
language: node_js
node_js: node
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - /^greenkeeper/.*$/
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script:
  - npm prune
  - greenkeeper-lockfile-update
script:
  - npm run test
after_script:
  - greenkeeper-lockfile-upload
after_success:
  - npm run semantic-release
notifications:
  email: false
