sudo: false
language: node_js
node_js: node
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - /^greenkeeper/.*$/
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - npm start lint
  - xvfb-run npm start test.sauce
  - npm start test
after_success:
  - npm start semantic-release
notifications:
  email: change
