sudo: false
language: node_js
node_js: node
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - /^greenkeeper/.*$/
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npm run semantic-release
notifications:
  email: false
