sudo: false
language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
before_script:
- npm prune
script:
- npm run test
after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run semantic-release; fi
notifications:
  email: false
