sudo: false
language: node_js
node_js: stable
cache: npm
branches:
  only:
    - master
    - /^greenkeeper/.*$/
script:
  - npm start lint
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then npm start test.sauce; fi
  - npm start test
after_success:
  - npm start report-coverage
  - npm start semantic-release
notifications:
  email: change
