name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  install:
    name: Install
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node--${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm i


  browserstack:
    name: Browserstack
    runs-on: ubuntu-18.04
    if: github.ref == 'refs/heads/master'
    needs: install

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Restore node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node--${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Run Tests
        if: github.ref == 'refs/heads/master'
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        run: npm start test.ci

  validate:
    name: Validate
    runs-on: ubuntu-18.04
    needs: install

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Restore node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node--${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Run Tests
        run: npm start test
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Release
    runs-on: ubuntu-18.04
    needs: [browserstack, validate]
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Restore node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node--${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      # Release the Codes!!
      - name: Release!
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm start semantic-release
